name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  pull_request:

jobs:

  populate-labels:
    name: Populate labels
    if: github.base_ref == 'main'
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/populate-labels.yaml@manos-backport-automation
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      track_file_path: ".github/automatic_backport_tracks.yaml"
      label_prefix: "backport "

  tests:
    name: Run Tests
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
